### ISSUE TITLE
Breaks when trying to address parent namespaces

### ISSUE THREAD

**Issue by malakai97** [jah2488/namespacing#3]
Given a file bug2.rb:

``` ruby
require 'namespacing'

class Object
  include Namespacing
end

module Foo
  module Bar
    class Base
    end
  end
end

ns "foo.bar.baz" do
  class BigBaz < Bar::Base
  end
end

```

Gives:

```
$ bundle exec ruby bug2.rb 
bug2.rb:15:in `block in <main>': uninitialized constant Bar (NameError)
    from /home/bhock/code/namespacing/lib/namespacing.rb:13:in `module_exec'
    from /home/bhock/code/namespacing/lib/namespacing.rb:13:in `make_namespaces'
    from /home/bhock/code/namespacing/lib/namespacing.rb:3:in `ns'
    from bug2.rb:14:in `<main>'
```

**Comment by malakai97** [comment]
Compare to:

``` ruby
module Foo
  module Bar
    class Base
    end
  end
end

module Foo
  module Bar
    module Baz
      class BigBaz < Bar::Base
      end
    end
  end
end
```

Which runs fine.
